site_name: My Awesome Project
site_description: A short description of my project.
site_author: Your Name
repo_url: https://github.com/yourusername/yourproject

theme:
  name: 'material'
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - test: test.md

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
