site_name: My Awesome Project
site_description: A short description of my project.
site_author: Your Name
repo_url: https://github.com/yourusername/yourproject

theme:
  name: 'material'
  # Optional: Some Material for MkDocs configuration options:
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - 2025:
    - NHI1:2025 testtest: 2025/test.md
    - NHI1:2025 testtest1: 2025/test.md

# Optional: Additional configuration for plugins, markdown extensions, etc.
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
  # If you have Material’s Insiders features or extra plugins, you can add them here.
