name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      # Install Jekyll dependencies
      - name: Install Jekyll dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Set up Python for MkDocs
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install MkDocs dependencies
      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      # Build 2025 site using MkDocs
      - name: Build MkDocs site
        working-directory: ./2025
        run: mkdocs build

      # Move compiled 2025 site into Jekyll's directory
      - name: Move MkDocs output
        run: |
          rm -rf _site/2025
          mkdir -p _site/2025
          mv 2025/site/* _site/2025/

      # Deploy to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
